---
title: "Coral holobiont - Map of distribution of metagenomic samples"
author: "Cavalcante et al."
date: "August 9, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggmap)
library(ggplot2)
library(RColorBrewer)
library(dplyr)
library(tidyr)
library(reshape2)
library(svglite)
```

## Data importing and sorting

```{r load}
# sample coordenates - must contain sample ID, latitude, logitude in this order
geral <-read.csv("map_coordenades_coral_metagenome_6mai2019.csv", sep=",", header=TRUE)

# adding growth form info desse novo arquivo
data <- read.csv("refined_detailed_abundance_phyla_157_corais_matrix_porcentagem_prot_divided_17abr2020.csv", 
                 check.names=FALSE)
data <- data.frame(data, check.names=FALSE)

geral_gf <- cbind(geral, gf = data$growth_form)

# sorting by growth form
data_prep <- data.frame(geral_gf) %>% 
                melt(id = c("gf", "genus")) %>%
                arrange(gf, genus)

genus_ord <- data_prep %>% pull(genus) %>% as.character() %>% unique()
```

## PLotting figure and saving

```{r}
# creating map layer
mp <- NULL
mapWorld <- borders("world", colour="black", fill="grey80", size=0.1) # create a layer of borders

# plotting map
basic_map <- ggplot(ungroup(geral_gf)) + 
  mapWorld +
  geom_count(aes(x = as.numeric(longitude), y = as.numeric(latitude), color = genus)) + #alpha=I(0.4)))+
  geom_count(data = filter(geral_gf, genus == "Montastrea"), aes(x = as.numeric(longitude), y = as.numeric(latitude), color = genus)) +
  scale_colour_manual(values=c("Acropora" = "#9400D3", 
                               "Pocillopora" = "hotpink3", 
                               "Seriatopora" = "lightsalmon",
                               "Madracis" = "#DEB887",
                               "Porites" = "green" , 
                               "Mussismilia" = "indianred4",
                               "Orbicella" = "chocolate", 
                               "Platygyra" = "lightgreen",
                               "Montipora" = "darkolivegreen",
                               "Siderastrea" = "darkslateblue", 
                               "Cyphastrea" = "steelblue3", 
                               "Diploria" = "blue", 
                               "Montastrea" = "orange"), 
                      breaks = genus_ord) + 

  scale_size_continuous(breaks = c(1, 10, 30, 60)) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  theme_bw() + 
  labs(color="Coral genus", size = "Number of samples") +
  theme(axis.line=element_blank(), 
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        legend.position="bottom",
        panel.background=element_blank(), 
        panel.border=element_blank(), 
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(), 
        plot.background=element_blank())

ggsave(file="map_coral_holobiont_09ago2020.png", plot=basic_map, width=9, height=5.5)
ggsave(file="map_coral_holobiont_09ago2020.svg", plot=basic_map, width=9, height=5.5)

```

